// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecsvsqczwknckbbbfngn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjc3ZzcWN6d2tuY2tiYmJmbmduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0ODk1NjMsImV4cCI6MjA5MDA2NTU2M30.F3g3W0eZVk-MDJW6z1FQW78BaxmRBsgmXjSmir3SSPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);